[target.bpfel-unknown-none]
rustflags = [
    "-C", "linker=sbpf-linker",
    "-C", "panic=abort",
    "-C", "relocation-model=static",
    "-C", "link-arg=--export=__multi3",
    "-C", "link-arg=--arch=v3",
    "-C", "link-arg=--llvm-args=-bpf-stack-size=4096",
    "-C", "link-arg=--llvm-args=--bpf-max-stores-per-memfunc=5",
    "-C", "link-arg=--llvm-args=--disable-gotox",
    "-C", "link-arg=--llvm-args=--disable-ldsx",
    "-C", "link-arg=--llvm-args=--disable-movsx",
    "-C", "target-cpu=v4",
    "-C", "target-feature=+allows-misaligned-mem-access",
    "--cfg", 'target_os="solana"',
    "--cfg", 'target_feature="static-syscalls"',
    "-A", "explicit_builtin_cfgs_in_flags",
]

[unstable]
build-std = ["core", "alloc"]
