[package]
name = "pinocchio-token-program"
version = "0.0.0"
description = "A pinocchio-based Token (aka 'p-token') program"
authors = { workspace = true}
repository = { workspace = true}
license = { workspace = true}
edition = { workspace = true}
readme = "./README.md"

[lib]
crate-type = ["cdylib"]

[features]
logging = []

[dependencies]
pinocchio = { workspace = true }
pinocchio-log = { version = "0.5.1", default-features = false }
pinocchio-pubkey = "0.3"
pinocchio-token-interface = { version = "^0", path = "../interface" }
solana-compiler-builtins = { git = "https://github.com/blueshift-gg/solana-compiler-builtins", branch = "main" }

[dev-dependencies]
assert_matches = "1.5.0"
mollusk-svm = "=0.15.1"
mollusk-svm-fuzz-fixture = "=0.15.1"
num-traits = { workspace = true }
solana-account = "4.3.1"
solana-instruction = { workspace = true }
solana-keypair = "3.0.0"
solana-program-error = { workspace = true }
solana-program-option = { workspace = true }
solana-program-pack = { workspace = true }
solana-program-test = { version = "=4.2.1", features = ["agave-unstable-api"] }
solana-pubkey = { workspace = true }
solana-rent = "4.2.1"
solana-sdk-ids = "3.0.0"
solana-signature = "3.0.0"
solana-signer = "3.0.0"
solana-transaction = "4.1.4"
solana-transaction-error = "3.0.0"
solana-system-interface = { workspace = true }
spl-token-interface = { workspace = true }
spl-token-2022-interface = "2"

[lints]
workspace = true

[package.metadata.solana]
program-id = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
